services:
  mysql:
    image: 'mysql:9.2'
    environment:
      - 'MYSQL_DATABASE=calendar'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=secret'
      - 'MYSQL_USER=user'
    ports:
      - '3306:3306'
